#!/bin/bash

find /bin /etc /var -maxdepth 3 -not -type p -exec md5sum {} 1>output.txt 2>error.txt \;

HASH=$(cat output.txt | wc -l)
NOHASH=$(cat error.txt | wc -l)

echo "Successfully Hashed Files: $HASH"
echo "Unsuccessfully Hashed FILES: $NOHASH"
