#!/bin/bash

FILES=$(find /etc -type f 2>/dev/null)

for FILE in $FILES;
do
    OCTAL=$(stat $FILE | sed -n 4p | cut -d"(" -f2 | cut -d/ -f1 | cut -c2-)
    if [[ $OCTAL == 642 ]]; then
        echo $OCTAL >> high.txt
    else
        echo $OCTAL >> low.txt
    fi
done

cat high.txt | sort | uniq -c


echo "Files w/ OCTAL Perm Values 642+:\n\t
